### PR TITLE
New core thrusters sprite 2: Electric Boogaloo

### PR DESCRIPTION
**Pull request by SunkyMP3G**
**Details:**
Made a new sprites for core thrusters. Again.

**Screenshots:**
image. Again.

---

- [x] I made sure that any changes made in this Pull Request functions correctly in-game.

### CODE REVIEW

**Comment by JojoFR1** [comment]
Can you show full landing animation (GIF or video)?

**Comment by SunkyMP3G** [comment]
I thought you saw it after the first PR...
You can see it by downloading the version before you Java'ed the mod, where the sprites were

**Comment by JojoFR1** [comment]
Oh is it the same?
I thought you just changed them

**Comment by SunkyMP3G** [comment]
They're same, that's why I named this pr as "2", they were erased after the Java'ing

**Comment by JojoFR1** [comment]
Really? I didn't removed any file, except for renaming

**Comment by SunkyMP3G** [comment]
In both branches
image

**Pull request merged**
