### PR TITLE
Turret lol)

### PR DESCRIPTION
**Pull request by RouterXdd**
**Details:**
Add the turret, who bullet pierce the enemies
Spit rarely shoots, but bullets debuffs the unit when hit
+Loadout schematic for planet

**Screenshots:**
Turret:
Снимок экрана 2023-07-10 163017
Spit's new status:
image

---

- [X] I made sure that any changes made in this Pull Request functions correctly in-game.

### CODE REVIEW

**Comment by RouterXdd** [comment]
image
Set speed multiplier to 0.8
Set health multiplier to 0.8

**Comment by JojoFR1** [comment]
So less health and slower for X amount of times right?

**Comment by RouterXdd** [comment]
It is not a stackable status

**Comment by SunkyMP3G** [comment]
Just 80% of HP and 80% of speed

**Pull request merged**
