### PR TITLE
Ru news update

### PR DESCRIPTION
**Pull request by SunkyMP3G**
Added a second note in Ru translations

### CODE REVIEW

**Comment by JojoFR1** [comment]
What's the line that you added

**Comment by SunkyMP3G** [comment]
Added 12-13 lines, added date in 9 line

**Comment by JojoFR1** [comment]
Yeah but what is it the new line

**Comment by SunkyMP3G** [comment]
These are just notes just ru people
First note says I'm at the vacation
Second says translation is ready

**Pull request merged**
